# General configuration

version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

# Environment configuration

image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

clone_depth: 1

environment:
  AWS_ACCESS_CLIENT_ID:
    secure: 7mjagrvKpawI4d3QxIUa6fXlvxQm6C3d3DMI7S2WGlY=
  AWS_SECRET_ACCESS_KEY:
    secure: EPjzIETUdn275EWUFFOADjM3De/DpJ1gdVINaJa2by4XHeXkOTrqwHtl60FG+SF4
  AWS_REGION: us-west-2

# Build configuration

configuration: Release

before_build:
  - dotnet --version
  - dotnet restore --verbosity m
  - nuget restore
  # Install AWS cli
  - aws --version
  #-Install AWS SAM CLI
  # - cmd: msiexec /qn /l* node-log.txt /i node-v12.16.1-x64.msi
  #- msiexec /i https://github.com/awslabs/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi /quiet
  - ps: Invoke-WebRequest -Uri https://github.com/awslabs/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi -OutFile aws-sam-cli.msi
  - cmd: msiexec /qn /l* aws-log.txt /i aws-sam-cli.msi
  - cmd: sleep 120
  - cmd: cat aws-log.txt
  - cmd: sam --version
  
build_script:
  - cmd: sam build

after_build:
  - choco install opencover.portable
  - choco install codecov

# Tests configuration

test_script:
  - OpenCover.Console.exe
    -target:"C:\Program Files\dotnet\dotnet.exe"
    -targetargs:"test"
    -output:coverage.xml
    -oldStyle
    -filter:"+[HelloWorld*]* -[HellowWorld.Tests*]*"
    -register:user
    -returntargetcode
  - codecov -f "coverage.xml"

# Artifacts configuration

artifacts:
  - path: \src\HelloWorld\bin\Release\netcoreapp2.1\publish
    name: artifact
    type: zip

# Deployment configuration

deploy_script:
  - cmd: sam deploy
