AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for Pecuniary.TimeSeries

Globals:
  Function:
    Timeout: 30

Resources:
  TimeSeriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Pecuniary.TimeSeries/
      Handler: Pecuniary.TimeSeries::Pecuniary.TimeSeries.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Policies:
        - AdministratorAccess
        #- Statement:
        #  - Effect: Allow
        #    Action:
        #      - dynamodb:*
        #    Resource: "*"
      Events:
        TimeSeries:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TimeSeriesApi:
    Description: "API Gateway endpoint URL for Prod stage for Pecuniary.TimeSeries function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TimeSeriesFunction:
    Description: "Pecuniary.TimeSeries Lambda Function ARN"
    Value: !GetAtt TimeSeriesFunction.Arn
  TimeSeriesFunctionIamRole:
    Description: "Implicit IAM Role created for Pecuniary.TimeSeries function"
    Value: !GetAtt TimeSeriesFunctionRole.Arn
