AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for Pecuniary.TimeSeries

Globals:
  Function:
    Timeout: 30

Resources:
  TimeSeriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Pecuniary.TimeSeries/
      Handler: Pecuniary.TimeSeries::Pecuniary.TimeSeries.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
              - dynamodb:Scan
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TimeSeries-*
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: "*" #!Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/AlphaVantageApiKey*
      Environment:
        Variables:
          TableName: TimeSeries-5xjfz6mpa5g2rgwc47wfyqzjja-dev
      Events:
        TimeSeries:
          Type: Api
          Properties:
            Path: /timeseries
            Method: post

Outputs:
  TimeSeriesApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/timeseries/"
  TimeSeriesFunction:
    Description: "Pecuniary.TimeSeries Lambda Function ARN"
    Value: !GetAtt TimeSeriesFunction.Arn
  TimeSeriesFunctionIamRole:
    Description: "Implicit IAM Role created for Pecuniary.TimeSeries function"
    Value: !GetAtt TimeSeriesFunctionRole.Arn
